package io.xmlss.elements

import java.awt.Color

class Color(val color: String) {
    constructor(color: Color) : this(String.format("#%06X", (0xFFFFFF and color.getRGB())))

    init {
        require(color.matches(Regex("#[\\daAbBcCdDeEfF]{6}"))) {
            "Color can be either a 6-hexadecimal digit number in \"#rrggbb\" format"
        }
    }

    companion object {
        val ALICEBLUE = Color("#F0F8FF")
        val ANTIQUEWHITE = Color("#FAEBD7")
        val AQUA = Color("#00FFFF")
        val AQUAMARINE = Color("#7FFFD4")
        val AZURE = Color("#F0FFFF")
        val BEIGE = Color("#F5F5DC")
        val BISQUE = Color("#FFE4C4")
        val BLACK = Color("#000000")
        val BLANCHEDALM = Color("#FFEBCD")
        val BLUE = Color("#0000FF")
        val BLUEVIOLET = Color("#8A2BE2")
        val BROWN = Color("#A52A2A")
        val BURLYWOOD = Color("#DEB887")
        val CADETBLUE = Color("#5F9EA0")
        val CHARTREUSE = Color("#7FFF00")
        val CHOCOLATE = Color("#D2691E")
        val CORAL = Color("#FF7F50")
        val CORNFLRBL = Color("#6495ED")
        val CORNSILK = Color("#FFF8DC")
        val CRIMSON = Color("#DC143C")
        val CYAN = Color("#00FFFF")
        val DARKBLUE = Color("#00008B")
        val DARKCYAN = Color("#008B8B")
        val DARKGROD = Color("#B8860B")
        val DARKGRAY = Color("#A9A9A9")
        val DARKGREEN = Color("#006400")
        val DARKKHAKI = Color("#BDB76B")
        val DKMAG = Color("#8B008B")
        val DOLVGREEN = Color("#556B2F")
        val DARKORANGE = Color("#FF8C00")
        val DARKORCHID = Color("#9932CC")
        val DARKRED = Color("#8B0000")
        val DKSALMON = Color("#E9967A")
        val DKSEAGREEN = Color("#8FBC8B")
        val DKSLATEBLUE = Color("#483D8B")
        val DKSLATEGRAY = Color("#2F4F4F")
        val DKTURQUOISE = Color("#00CED1")
        val DAKVIOLET = Color("#9400D3")
        val DEEPPINK = Color("#FF1493")
        val DEEPSKYBLUE = Color("#00BFFF")
        val DIMGRAY = Color("#696969")
        val DODGERBLUE = Color("#1E90FF")
        val FIREBRICK = Color("#B22222")
        val FLORALWHITE = Color("#FFFAF0")
        val FORESTGR = Color("#228B22")
        val FUCHSIA = Color("#FF00FF")
        val GAINSBORO = Color("#DCDCDC")
        val GHOSTWH = Color("#F8F8FF")
        val GOLD = Color("#FFD700")
        val GOLDENROD = Color("#DAA520")
        val GRAY = Color("#808080")
        val GREEN = Color("#008000")
        val GRYELLOW = Color("#ADFF2F")
        val HONEYDEW = Color("#F0FFF0")
        val HOTPINK = Color("#FF69B4")
        val INDIANRED = Color("#CD5C5C")
        val INDIGO = Color("#4B0082")
        val IVORY = Color("#FFFFF0")
        val KHAKI = Color("#F0E68C")
        val LAVENDER = Color("#E6E6FA")
        val LAVBLUSH = Color("#FFF0F5")
        val LAWNGREEN = Color("#7CFC00")
        val LEMONCHIFFON = Color("#FFFACD")
        val LIGHTBLUE = Color("#ADD8E6")
        val LIGHTCORAL = Color("#F08080")
        val LIGHTCYAN = Color("#E0FFFF")
        val LIGHTGOLDENRODYELLOW = Color("#FAFAD2")
        val LIGHTGREEN = Color("#90EE90")
        val LIGHTGREY = Color("#D3D3D3")
        val LIGHTPINK = Color("#FFB6C1")
        val LIGHTSALMON = Color("#FFA07A")
        val LIGHTSEAGR = Color("#20B2AA")
        val LIGHTSKYBLUE = Color("#87CEFA")
        val LIGHTSLATEGRAY = Color("#778899")
        val LIGHTSTEELBLUE = Color("#B0C4DE")
        val LIGHTYELLOW = Color("#FFFFE0")
        val LIME = Color("#00FF00")
        val LIMEGREEN = Color("#32CD32")
        val LINEN = Color("#FAF0E6")
        val MAGENTA = Color("#FF00FF")
        val MAROON = Color("#800000")
        val MEDAQUA = Color("#66CDAA")
        val MEDBLUE = Color("#0000CD")
        val MEDORCHID = Color("#BA55D3")
        val MEDPURPLE = Color("#9370DB")
        val MEDSEAGREEN = Color("#3CB371")
        val MEDSLATEBLUE = Color("#7B68EE")
        val MEDSPRINGGREEN = Color("#00FA9A")
        val MEDTURQUOISE = Color("#48D1CC")
        val MEDVIOLETRED = Color("#C71585")
        val MIDBLUE = Color("#191970")
        val MINTCREAM = Color("#F5FFFA")
        val MISTYROSE = Color("#FFE4E1")
        val MOCCASIN = Color("#FFE4B5")
        val NAVAJOWHITE = Color("#FFDEAD")
        val NAVY = Color("#000080")
        val OLDLACE = Color("#FDF5E6")
        val OLIVE = Color("#808000")
        val OLIVEDRAB = Color("#6B8E23")
        val ORANGE = Color("#FFA500")
        val ORANGERED = Color("#FF4500")
        val ORCHID = Color("#DA70D6")
        val PALEGOLDENROD = Color("#EEE8AA")
        val PALEGREEN = Color("#98FB98")
        val PALETURQUOISE = Color("#AFEEEE")
        val PALEVIOLETRED = Color("#DB7093")
        val PAPAYAWHIP = Color("#FFEFD5")
        val PEACHPUFF = Color("#FFDAB9")
        val PERU = Color("#CD853F")
        val PINK = Color("#FFC0CB")
        val PLUM = Color("#DDA0DD")
        val POWDERBLUE = Color("#B0E0E6")
        val PURPLE = Color("#800080")
        val RED = Color("#FF0000")
        val ROSYBROWN = Color("#BC8F8F")
        val ROYALBLUE = Color("#4169E1")
        val SADDLEBROWN = Color("#8B4513")
        val SALMON = Color("#FA8072")
        val SANDYBROWN = Color("#F4A460")
        val SEAGREEN = Color("#2E8B57")
        val SEASHELL = Color("#FFF5EE")
        val SIENNA = Color("#A0522D")
        val SILVER = Color("#C0C0C0")
        val SKYBLUE = Color("#87CEEB")
        val SLATEBLUE = Color("#6A5ACD")
        val SLATEGRAY = Color("#708090")
        val SNOW = Color("#FFFAFA")
        val SPRINGGREEN = Color("#00FF7F")
        val STEELBLUE = Color("#4682B4")
        val TAN = Color("#D2B48C")
        val TEAL = Color("#008080")
        val THISTLE = Color("#D8BFD8")
        val TOMATO = Color("#FF6347")
        val TURQUOISE = Color("#40E0D0")
        val VIOLET = Color("#EE82EE")
        val WHEAT = Color("#F5DEB3")
        val WHITE = Color("#FFFFFF")
        val WHITESMOKE = Color("#F5F5F5")
        val YELLOW = Color("#FFFF00")
        val YELLOWGR = Color("#9ACD32")
    }

    override fun toString() = color

}